name: Ba Sing Se Docker Build and Push

on:
  push:
    branches: [ "main" ]
    paths: [ "services/ba-sing-se/**"]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Image tag
      run: echo "DOCKER_IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

    - name: Build the Docker image
      run: docker build services/ba-sing-se --tag ${{ secrets.DOCKER_USER }}/ba-sing-se:${{ env.DOCKER_IMAGE_TAG }}

    - name: Push the Docker image
      run: docker push -a ${{ secrets.DOCKER_USER }}/ba-sing-se

    - name: Tag the Docker image
      run: docker tag ${{ secrets.DOCKER_USER }}/ba-sing-se:${{ env.DOCKER_IMAGE_TAG }} ${{ secrets.DOCKER_USER }}/ba-sing-se:latest
